knp_paginator:
    page_range: 5
    default_options:
        sort_field_name: null
        sort_direction_name: null
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
